#line 2 "lex.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = (int) (yy_cp - yytext_ptr); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 86
#define YY_END_OF_BUFFER 87
static yyconst short int yy_accept[306] =
    {   0,
        0,    0,    0,    0,   87,   85,   70,   70,   85,   85,
       85,   69,   69,   73,   69,   69,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   56,   69,
       80,   58,   80,   80,   80,   80,   59,   57,    0,   82,
        0,    0,    0,   84,   83,   75,    0,   74,   73,    0,
       67,   66,   68,   80,   80,   80,   80,    3,   80,   80,
        6,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   13,   16,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   33,   20,   80,   80,   80,

       80,   80,   80,   80,   80,   80,   80,   80,   80,   55,
       55,   55,   80,   80,   65,   80,   63,   60,   81,    0,
        0,    0,    0,    0,   74,    0,    0,   76,   34,    1,
        2,    4,   45,   80,   80,   80,   80,   80,   37,   39,
       80,   80,   43,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   51,   80,   40,   48,   47,   36,   18,
       80,   42,   80,   80,   80,   80,   80,   80,   23,   80,
       80,   44,   80,   80,   80,   80,   80,   55,   55,   80,
       80,   80,    0,    0,    0,    0,    0,   75,    0,    0,
       74,   80,   80,   80,    8,   80,   80,   80,   10,   30,

       80,   80,   80,   80,   15,   27,   50,   31,   17,   19,
       80,   80,   80,   80,   80,   80,   35,   38,   80,   71,
       80,   80,   80,   55,   55,   55,   64,   80,   61,    0,
        0,    0,   54,   80,   46,   80,   80,   72,   49,   11,
       80,   28,   80,   21,   29,   53,   41,   32,   80,   80,
       80,   80,   26,   54,   80,    0,    0,    0,   80,    7,
       80,   12,   14,   22,   80,   24,   25,   62,    0,    0,
        0,    5,   80,   80,   77,    0,    0,   79,    0,    9,
       80,    0,    0,    0,   52,    0,    0,   78,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    6,    7,
        7,    7,    8,    7,    8,    9,   10,   11,   11,   12,
       12,   12,   12,   12,   12,   12,   12,   13,    7,   14,
       15,   16,    7,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
        1,    1,    1,    1,   17,    1,   18,   19,   20,   21,

       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   44,    1,   45,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[46] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        4,    4,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    1,    1
    } ;

static yyconst short int yy_base[310] =
    {   0,
        0,  412,   26,   63,  420,  422,  422,  422,  416,   40,
       50,  422,   43,   48,   46,  403,   60,   46,  385,   43,
      375,   72,  380,  396,   42,  381,    0,   79,   48,   43,
       78,   80,  386,   92,  376,  377,  391,  383,  422,   81,
       85,   97,   84,  103,   29,   97,  101,  422,  136,  422,
      133,  137,  144,  422,  422,  140,  369,  142,  146,  148,
      422,  422,  422,    0,  370,  376,  383,  383,  378,  364,
        0,  362,  134,  130,  366,  369,  362,  359,  363,  365,
      361,  353,  136,    0,  365,  354,  148,  361,  364,  346,
      355,  364,  347,  354,  353,    0,  360,  343,  340,  338,

      353,  145,  352,  340,  344,  143,  352,  343,  349,    0,
      164,  332,  340,  348,    0,  341,    0,    0,  422,  166,
      174,  353,  177,  339,  179,  184,  182,  186,    0,    0,
        0,    0,    0,  324,  332,  340,  341,  323,    0,    0,
      323,  322,    0,  327,  327,  317,  328,  331,  330,  319,
      319,  312,  311,    0,  325,    0,    0,    0,    0,    0,
      317,    0,  323,  322,  311,  320,  316,  318,    0,  308,
      301,    0,  306,  314,  317,  296,  298,  191,  306,  302,
      312,  308,  195,  319,  316,  197,  199,  201,  289,  203,
      205,  303,  287,  286,    0,  296,  299,  283,    0,    0,

      286,  287,  282,  281,    0,    0,    0,    0,    0,    0,
      280,  279,  276,  277,  274,  290,    0,    0,  273,    0,
      271,  285,  284,  207,  209,  268,    0,  271,    0,  211,
      213,  215,  422,  281,    0,  280,  270,    0,    0,    0,
      276,    0,  262,    0,    0,    0,    0,    0,  261,  274,
      274,  259,    0,    0,  270,  217,  275,  267,  248,    0,
      258,    0,    0,    0,  206,    0,    0,    0,  225,  220,
      228,    0,  168,  165,  422,  223,  230,  422,  232,    0,
      150,  240,  243,  160,    0,  235,  238,  422,  245,  130,
      247,  255,  118,  250,  252,  260,  114,  258,  262,  109,

       99,  270,  265,   89,  422,  282,  286,   72,  290
    } ;

static yyconst short int yy_def[310] =
    {   0,
      305,    1,    1,    1,  305,  305,  305,  305,  306,  305,
      307,  305,  305,  305,  305,  305,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  305,  309,
      308,  308,  308,  308,  308,  308,  308,  305,  306,  305,
      305,  305,  307,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  309,
      309,  309,  308,  308,  308,  308,  308,  308,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  309,  309,  308,
      308,  308,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  309,  309,  309,  308,  308,  308,  305,
      305,  305,  305,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  309,  308,  305,  305,  305,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  305,  305,
      305,  308,  308,  308,  305,  305,  305,  305,  305,  308,
      308,  305,  305,  305,  308,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,

      305,  305,  305,  305,    0,  305,  305,  305,  305
    } ;

static yyconst short int yy_nxt[468] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   12,   13,   12,
       14,   14,   12,   15,   12,   16,    6,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   27,   33,   34,   35,   36,   37,   38,
       27,   27,   27,   39,   12,   41,   42,   43,   44,   45,
       51,   52,   54,   56,   56,   55,   58,   46,   59,   59,
       61,   62,   47,   81,   73,   90,  116,   70,   74,   60,
       48,   40,   83,   91,   93,   64,   57,   84,   65,   92,
       94,   95,   41,   42,   43,   44,   45,   71,   66,   76,
       67,  111,  111,  288,   46,   68,   86,   77,   69,   47,

       87,   78,  113,  275,   88,   99,   79,   48,   96,   80,
       89,  100,   97,  102,  112,   98,   72,  103,   73,  114,
       76,  302,   74,  117,   75,  104,  295,   96,   77,  105,
      296,   97,   78,  115,   98,  106,  118,   79,   50,  119,
       80,  120,  287,  121,  121,  120,   54,  122,  122,   55,
       56,   56,  125,  125,   58,  127,   59,   59,  128,  128,
      173,  123,  136,  126,  278,  138,  148,   60,  139,  137,
      153,  149,  150,  168,  111,  111,  183,  184,  154,  285,
      174,  169,  120,  185,  187,  178,  186,  188,  188,  125,
      125,  190,  128,  128,  191,  191,  128,  128,  224,  281,

      126,  225,  225,  230,  280,  184,  184,  232,  232,  188,
      188,  188,  188,  191,  191,  191,  191,  225,  225,  225,
      225,  256,  256,  257,  257,  258,  258,  269,  269,  275,
      277,  277,  278,  282,  282,  276,  276,  274,  279,  279,
      283,  283,  284,  284,  275,  290,  290,  288,  291,  291,
      286,  286,  287,  289,  289,  292,  292,  293,  293,  288,
      297,  297,  298,  298,  275,  294,  294,  295,  300,  300,
      299,  299,  301,  301,  288,  304,  304,  273,  272,  271,
      303,  303,   49,   49,  270,   49,   53,   53,   53,   53,
      110,  268,  110,  110,  267,  266,  265,  264,  263,  262,

      261,  260,  259,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  240,  239,
      238,  237,  236,  235,  234,  233,  231,  230,  229,  228,
      227,  226,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  214,  213,  212,  211,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  189,  186,  182,  181,  180,  179,
      177,  176,  175,  172,  171,  170,  167,  166,  165,  164,
      163,  162,  161,  160,  159,  158,  157,  156,  155,  152,
      151,  147,  146,  145,  144,  143,  142,  141,  140,  135,

      134,  133,  132,  131,  130,  129,  124,  109,  108,  107,
      106,  101,   85,   82,   81,   75,   72,   63,   50,  305,
       40,    5,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305
    } ;

static yyconst short int yy_chk[468] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
       10,   10,   11,   13,   13,   11,   14,    3,   14,   14,
       15,   15,    3,   45,   20,   29,   45,   18,   20,   14,
        3,    4,   25,   29,   30,  308,   13,   25,   17,   29,
       30,   30,    4,    4,    4,    4,    4,   18,   17,   22,
       17,   40,   40,  304,    4,   17,   28,   22,   17,    4,

       28,   22,   41,  301,   28,   32,   22,    4,   31,   22,
       28,   32,   31,   34,   40,   31,   41,   34,   42,   43,
       44,  300,   42,   46,   43,   34,  297,   46,   44,   34,
      293,   46,   44,   44,   46,   47,   47,   44,   49,   49,
       44,   51,  290,   51,   51,   52,   53,   52,   52,   53,
       56,   56,   58,   58,   59,   60,   59,   59,   60,   60,
      106,   56,   73,   58,  284,   74,   83,   59,   74,   73,
       87,   83,   83,  102,  111,  111,  120,  120,   87,  281,
      106,  102,  121,  121,  123,  111,  121,  123,  123,  125,
      125,  126,  127,  127,  126,  126,  128,  128,  178,  274,

      125,  178,  178,  183,  273,  183,  183,  186,  186,  187,
      187,  188,  188,  190,  190,  191,  191,  224,  224,  225,
      225,  230,  230,  231,  231,  232,  232,  256,  256,  269,
      270,  270,  271,  276,  276,  269,  269,  265,  271,  271,
      277,  277,  279,  279,  282,  286,  286,  283,  287,  287,
      282,  282,  282,  283,  283,  289,  289,  291,  291,  292,
      294,  294,  295,  295,  296,  292,  292,  292,  298,  298,
      296,  296,  299,  299,  302,  303,  303,  261,  259,  258,
      302,  302,  306,  306,  257,  306,  307,  307,  307,  307,
      309,  255,  309,  309,  252,  251,  250,  249,  243,  241,

      237,  236,  234,  228,  226,  223,  222,  221,  219,  216,
      215,  214,  213,  212,  211,  204,  203,  202,  201,  198,
      197,  196,  194,  193,  192,  189,  185,  184,  182,  181,
      180,  179,  177,  176,  175,  174,  173,  171,  170,  168,
      167,  166,  165,  164,  163,  161,  155,  153,  152,  151,
      150,  149,  148,  147,  146,  145,  144,  142,  141,  138,
      137,  136,  135,  134,  124,  122,  116,  114,  113,  112,
      109,  108,  107,  105,  104,  103,  101,  100,   99,   98,
       97,   95,   94,   93,   92,   91,   90,   89,   88,   86,
       85,   82,   81,   80,   79,   78,   77,   76,   75,   72,

       70,   69,   68,   67,   66,   65,   57,   38,   37,   36,
       35,   33,   26,   24,   23,   21,   19,   16,    9,    5,
        2,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  305,  305
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\lex.l"
#define INITIAL 0
#line 2 ".\\lex.l"
/****************************************************************************
lexer.l
Lexical analyser for a simple calculator. The lexical analyser is
implemented using a C++ class. This is specified by selecting the -Tcpp
option in ALex (the "C++" selection from the Target Language combo box in
the ALex Options dialog box).
****************************************************************************/

#pragma warning(disable : 4786)
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <assert.h>
#include <errno.h>

#include <string>
#include "sqlp.h"

//---------------------------------------------------------------------------
// Lexer Declarations
//---------------------------------------------------------------------------
#include "yac.h"
namespace sqlp 
{
	CStatement * m_stmt;
}
//using namespace sqlp;
//---------------------------------------------------------------------------
// Lexer Defines
//---------------------------------------------------------------------------
//#define YY_DECL int yylex (YYSTYPE & yylval)
//#define YY_INPUT(b,r,s) (r = yyinput(b,s))


//---------------------------------------------------------------------------
// LEX - Defintions
//---------------------------------------------------------------------------
/* macros */
#define SQLESC 1

//---------------------------------------------------------------------------
// LEX - Rules
//---------------------------------------------------------------------------
#line 617 "lex.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 54 ".\\lex.l"


 /*************************************
  LITERALS KEYWORDS TOKENS
  ************************************/
#line 777 "lex.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yy_c_buf_p - yytext_ptr;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 306 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 422 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 59 ".\\lex.l"
{ return lALL; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 60 ".\\lex.l"
{ return lAND; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 61 ".\\lex.l"
{ return lAS; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 62 ".\\lex.l"
{ return lASC; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 ".\\lex.l"
{ return lBETWEEN; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 64 ".\\lex.l"
{ return lBY; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 65 ".\\lex.l"
{ return lDELETE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 66 ".\\lex.l"
{ return lDESC; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 67 ".\\lex.l"
{ return lDISTINCT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 68 ".\\lex.l"
{ return lFROM; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 69 ".\\lex.l"
{ return lGROUP; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 70 ".\\lex.l"
{ return lHAVING; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 71 ".\\lex.l"
{ return lIN; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 72 ".\\lex.l"
{ return lINSERT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 73 ".\\lex.l"
{ return lINTO; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 74 ".\\lex.l"
{ return lIS; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 75 ".\\lex.l"
{ return lLIKE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 76 ".\\lex.l"
{ return lNOT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 77 ".\\lex.l"
{ return lNULL; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 78 ".\\lex.l"
{ return lOR; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 79 ".\\lex.l"
{ return lORDER; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 80 ".\\lex.l"
{ return lSELECT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 81 ".\\lex.l"
{ return lSET; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 82 ".\\lex.l"
{ return lUPDATE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 83 ".\\lex.l"
{ return lVALUES; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 84 ".\\lex.l"
{ return lWHERE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 86 ".\\lex.l"
{ return lJOIN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 87 ".\\lex.l"
{ return lINNER; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 88 ".\\lex.l"
{ return lOUTER; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 89 ".\\lex.l"
{ return lFULL; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 90 ".\\lex.l"
{ return lLEFT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 91 ".\\lex.l"
{ return lRIGHT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 92 ".\\lex.l"
{ return lON; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 94 ".\\lex.l"
{ return lABS; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 95 ".\\lex.l"
{ return lSIGN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 96 ".\\lex.l"
{ return lMOD; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 97 ".\\lex.l"
{ return lDIV; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 98 ".\\lex.l"
{ return lSQRT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 99 ".\\lex.l"
{ return lEXP; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 100 ".\\lex.l"
{ return lLOG; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 101 ".\\lex.l"
{ return lEXP; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 102 ".\\lex.l"
{ return lNVL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 104 ".\\lex.l"
{ return lFMT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 106 ".\\lex.l"
{ return lSUM; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 107 ".\\lex.l"
{ return lAVG; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 108 ".\\lex.l"
{ return lCOUNT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 109 ".\\lex.l"
{ return lMIN; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 110 ".\\lex.l"
{ return lMAX; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 111 ".\\lex.l"
{ return lFIRST; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 112 ".\\lex.l"
{ return lLAST; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 113 ".\\lex.l"
{ return lLEN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 115 ".\\lex.l"
{ return lTRANSFORM; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 116 ".\\lex.l"
{ return lPIVOT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 118 ".\\lex.l"
{ return yyexit(); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 119 ".\\lex.l"
{  
			yylval.string = m_stmt->atom (yytext+1);
			return lCMD;
			}			
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 124 ".\\lex.l"
{ BEGIN SQLESC; return '{'; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 125 ".\\lex.l"
{ BEGIN 0; return '}'; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 126 ".\\lex.l"
{ return lDATE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 127 ".\\lex.l"
{ return lTIME; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 128 ".\\lex.l"
{ return lTIMESTAMP; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 129 ".\\lex.l"
{ return lGUID; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 130 ".\\lex.l"
{ return lESCAPE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 131 ".\\lex.l"
{ return lOJ; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 132 ".\\lex.l"
{ return lCALL; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 133 ".\\lex.l"
{ return lFN; }
	YY_BREAK
/*************************************
  COMPARISON
  *************************************/
case 66:
YY_RULE_SETUP
#line 139 ".\\lex.l"
{ return lNEQ; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 140 ".\\lex.l"
{ return lLEQ; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 141 ".\\lex.l"
{ return lGEQ; }
	YY_BREAK
/*************************************
  PUNCTUATION
  *************************************/
case 69:
YY_RULE_SETUP
#line 146 ".\\lex.l"
{
			return yytext[0];
			}
	YY_BREAK
/*************************************
  white space
  *************************************/
case 70:
YY_RULE_SETUP
#line 153 ".\\lex.l"
{ /* do nothing */ }
	YY_BREAK
/*************************************
  BOOL
  *************************************/
case 71:
YY_RULE_SETUP
#line 158 ".\\lex.l"
{ yylval.number = 1; return lBOOLEAN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 159 ".\\lex.l"
{ yylval.number = 0; return lBOOLEAN; }
	YY_BREAK
/*************************************
  INTEGER
  *************************************/
case 73:
YY_RULE_SETUP
#line 164 ".\\lex.l"
{ yylval.number = yynumber(); return lINTEGER; }
	YY_BREAK
/*************************************
  NUMBER
  *************************************/
case 74:
#line 170 ".\\lex.l"
case 75:
#line 171 ".\\lex.l"
case 76:
YY_RULE_SETUP
#line 171 ".\\lex.l"
{ yylval.number = yynumber(); return lNUMBER; }
	YY_BREAK
/*************************************
  DATE/TIME
  *************************************/
case 77:
#line 177 ".\\lex.l"
case 78:
#line 178 ".\\lex.l"
case 79:
YY_RULE_SETUP
#line 178 ".\\lex.l"
{ yylval.datetime = yydatetime(); return lDATETIME; }
	YY_BREAK
/*************************************
  NAMES
  *************************************/
case 80:
YY_RULE_SETUP
#line 184 ".\\lex.l"
{
				std::string & aSQL = m_stmt->m_strSQL;
				if (aSQL.empty())
					yylval.string = yystring();
				else
					yylval.string = yystring();
					//yylval.string = m_stmt->sql (strlen(yytext), false);
				return lNAME;
			}
	YY_BREAK
/*************************************
  NAMES ([] quotetd)
  *************************************/
case 81:
YY_RULE_SETUP
#line 197 ".\\lex.l"
{
				std::string & aSQL = m_stmt->m_strSQL;
				if (!aSQL.empty())
				{
					yylval.string = m_stmt->atom (yytext+1, -1);
					return lNAME;
				}
				yylval.string = yystring();
				return lNAME;
		}			
	YY_BREAK
/*************************************
  NAMES (unterminated)
  *************************************/
case 82:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 211 ".\\lex.l"
{ 
			yyerror( "Unterminated string" ); 
		}
	YY_BREAK
/*************************************
  STRINGS (single quotes)
  NOTE: I recommend appending a space on the end of your statement because I
        have found that STRINGs will not get picked up if the last char in the
        statement is the closing quote of said STRING. - PAH
  *************************************/
case 83:
YY_RULE_SETUP
#line 221 ".\\lex.l"
{
			char * szBuff = strdup (yytext+1);
			const int n = strlen(szBuff);
			if (n > 0)
				szBuff[n - 1] = 0;
			const int c = yyinput();
			unput (c);
			if (c != '\'' && n > 1)
			{
				assert (m_stmt);
				yylval.string = szBuff;
				m_stmt->m_aAtoms.push_back (szBuff);
				//yylval.string = m_stmt->atom (szBuff);
				return lSTRING;
			}
			else
			{
				free (szBuff);
				yymore();
			}
		}
	YY_BREAK
/*************************************
  STRINGS (unterminated)
  *************************************/
case 84:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 246 ".\\lex.l"
{ 
			yyerror( "Unterminated string" ); 
		}
	YY_BREAK
/*************************************
  others
  *************************************/
case 85:
YY_RULE_SETUP
#line 253 ".\\lex.l"
{ printf("invalid character '0x%02x'\n", (unsigned int)yytext[0]); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SQLESC):
#line 255 ".\\lex.l"
{ return yyexit(); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 257 ".\\lex.l"
ECHO;
	YY_BREAK
#line 1384 "lex.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 306 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 306 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 305);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 257 ".\\lex.l"


//namespace sqlp {
//---------------------------------------------------------------------------
// Lexer commands
//---------------------------------------------------------------------------
int yyinputc (char * buff, int size)
{
#if 1
	int i,c;
	for (i=0; i<size; i++)
	{
		c = getc (yyin);
		if (c == EOF)
			return YY_NULL;
		buff[i] = c;
		if (c == '\n')
			break;
	}
	return i + 1;
#else
	int c = getchar();
	if (c == EOF)
		return YY_NULL;
	buff[0] = c;
	return 1;
#endif
}
//---------------------------------------------------------------------------
int yyinput (char * buff, int size)
{
	assert (m_stmt);
	std::string & aSQL = m_stmt->m_strSQL;
	ULONG & i = m_stmt->m_iSQL;
	if (aSQL.empty())
		return yyinputc (buff, size);
	if (i >= aSQL.length())
		return YY_NULL;
	const char * szSQL = aSQL.c_str();
	int n = strlen (szSQL);
	if (n > size)
		n = size;
	memcpy (buff, szSQL, n);
	i += n;
	return n;
}
//---------------------------------------------------------------------------
double yynumber()
{
	errno = 0;		// clear error flag
	char* endp;
	double d = strtod(yytext, &endp);
	if ((d == +HUGE_VAL || d == -HUGE_VAL) && errno == ERANGE) {
		printf("number too big\n");
	}
	return d;
}
//---------------------------------------------------------------------------
time_t yydatetime()
{
	errno = 0;		// clear error flag
	struct tm aTime;
	int n;

	const char * szTime = yytext + 1;
	memset (&aTime, 0, sizeof(aTime));
	n = sscanf (szTime, "%hu.%hu.%hu %hu:%hu:hu"
	, &aTime.tm_mday, &aTime.tm_mon, &aTime.tm_year
	, &aTime.tm_hour, &aTime.tm_min, &aTime.tm_sec);
	if (n < 3)
	n = sscanf (szTime, "%hu/%hu/%hu %hu:%hu:hu"
	, &aTime.tm_mon, &aTime.tm_year, &aTime.tm_mday
	, &aTime.tm_hour, &aTime.tm_min, &aTime.tm_sec);
	if (n < 3 || n == 4)
		return 0;
	if (aTime.tm_year > 1900)
		aTime.tm_year -= 1900;
	else
	{
		const time_t t0 = time(0);
		struct tm * pNow = localtime (&t0);
		aTime.tm_year %= 100;
		aTime.tm_year += pNow->tm_year - (pNow->tm_year % 100);
	}
	aTime.tm_mon--;
	time_t nTime = mktime (&aTime);
	return nTime;
}
//---------------------------------------------------------------------------
const char * yystring()
{
	assert (m_stmt);
	return m_stmt->atom (yytext);
}
//---------------------------------------------------------------------------
void yyinit (CStatement * pStmt, FILE* pFile)
{
	assert (pStmt);
	m_stmt = pStmt;
	const char * szSQL = pStmt->m_strSQL.c_str();
	yy_delete_buffer (yy_current_buffer);
	if (!pFile)
		yy_switch_to_buffer (yy_scan_string (szSQL));
	else
	{
		yyin = pFile;
		yy_switch_to_buffer (yy_create_buffer( yyin, YY_BUF_SIZE));
	}
}
//---------------------------------------------------------------------------
int yyexit()
{
	yy_delete_buffer (yy_current_buffer); 
	yy_current_buffer = 0;
	yy_init = 1;
	return YY_NULL;
}
//---------------------------------------------------------------------------
void yyerror (char const * err)
{
	fputs (err, stderr);
}
//---------------------------------------------------------------------------
//} // namespace